### ISSUE TITLE
net-ssh 5.0.2 Compatibility

### ISSUE THREAD

**Issue by sjafferali** [kt97679/one-ssh#3]
I receive this error with net-ssh 5.0.2 installed.
```
samir@macbook [~]$ ossh -H "portal" -l root -c "ls"
F, [2018-06-30T19:01:04.518248 #30595] FATAL -- : caught an error during initialization: uninitialized constant Net::SSH::Verifiers::Null
   /Library/Ruby/Gems/2.3.0/gems/em-ssh-0.8.1/lib/em-ssh/connection.rb:350:in `select_host_key_verifier'
   /Library/Ruby/Gems/2.3.0/gems/em-ssh-0.8.1/lib/em-ssh/connection.rb:196:in `initialize'
   /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:55:in `block in new'
   /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:49:in `instance_eval'
   /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/em/connection.rb:49:in `new'
   /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:683:in `bind_connect'
   /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:653:in `connect'
   /Library/Ruby/Gems/2.3.0/gems/em-ssh-0.8.1/lib/em-ssh.rb:125:in `connect'
   /Users/samir.jafferali/github/one-ssh/lib/ossh.rb:58:in `start_ssh'
   /Users/samir.jafferali/github/one-ssh/lib/ossh.rb:203:in `run'
   /Users/samir.jafferali/github/one-ssh/lib/ossh.rb:241:in `block (2 levels) in initialize'
   /Users/samir.jafferali/github/one-ssh/lib/ossh.rb:240:in `each'
   /Users/samir.jafferali/github/one-ssh/lib/ossh.rb:240:in `block in initialize'
portal uninitialized constant Net::SSH::Verifiers::Null (NameError)
portal double resume (FiberError)
samir@macbook [~]$
```

Downgrading to 4.2.0 works though. 
```
samir@macbook [~]$ ossh -H "portal" -l root -c "ls"
portal bin
samir@macbook [~]$
```

**Comment by kt97679** [comment]
Thanks for report @sjafferali , I'll take a look.

**Comment by kt97679** [comment]
This is because of incompatible change in net-ssh: https://github.com/net-ssh/net-ssh/commit/29a8e97ae8d2eaf674a8694b775dc119985fa5e9 Issue needs to be fixed in the em-ssh, here is related PR: https://github.com/gruis/em-ssh/pull/35

**Comment by kt97679** [comment]
em-ssh 0.8.2 was published, I verified that ossh works ok.
